name: Serverless Devs CI/CD

on:
  push:
    branches:
      - main # 或者根据您的项目使用'master'或其他分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Serverless Devs
        run: npm install -g @serverless-devs/s

      - name: Configure Serverless Devs
        run: |
          s config add --AccountID ${{secrets.ALIYUN_ACCOUNT_ID}} \
            --AccessKeyID ${{secrets.ALIYUN_ACCESS_KEY_ID}} \
            --AccessKeySecret ${{secrets.ALIYUN_ACCESS_KEY_SECRET}} \
            -a default

      - name: Deploy with Serverless Devs
        run: s deploy
